initial_positions:
  joint_00: 0
  joint_10: 0
  joint_11: 0
  joint_12: 0.25
  joint_13: 0
  joint_14: 0
  joint_15: 0
  joint_01: 0
  joint_02: 0
  joint_03: 0
  joint_04: 0
  joint_05: 0
  joint_06: 0
  joint_07: 0
  joint_08: 0
  joint_09: 0