<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <!-- Métadonnées de base -->
  <name>allegro_hand_controllers</name>
  <version>0.0.0</version>
  <description>Package containing the ros2_control hardware interface for the Allegro Hand.</description>
  <maintainer email="timothee.carecchio@inria.fr">tcarecch</maintainer>
  <license>Apache-2.0</license> <!-- Mettez la licence de votre choix, Apache-2.0 est un bon défaut -->

  <!-- Dépendance de l'outil de build -->
  <buildtool_depend>ament_cmake</buildtool_depend>

  <!-- Dépendances nécessaires pour compiler et exécuter -->
  <depend>rclcpp</depend>

  <!-- Dépendances pour les tests (bonne pratique) -->
  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <!-- Exportation des informations de build -->
  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>